spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/easydesk_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: fb7S@REuio~j[[j8HC`Pn=gG$HdH.8WCN8iT4QhXx27W]N0Uo

server:
  port: 8080

java:
  version: 21

# OpenAPI and Swagger Configuration
# OpenAPI and Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: "EasyDesk API"
    description: "API for EasyDesk Application"
    version: "1.0.0"
    contact:
      name: "Christian Estevam"
      email: "christianestevamb@gmail.com"
  security-schemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  security-enabled: true
