BEGIN;


CREATE TABLE IF NOT EXISTS public.cardapio
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    restaurante_id bigint NOT NULL,
    CONSTRAINT cardapio_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.cardapio_itens
(
    cardapio_id bigint NOT NULL,
    itens_id bigint NOT NULL,
    CONSTRAINT uktl48nqlfe96ekyota417v0wy3 UNIQUE (itens_id)
    );

CREATE TABLE IF NOT EXISTS public.cliente
(
    cnpj_cpf character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telefone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id bigint NOT NULL,
    CONSTRAINT cliente_pkey PRIMARY KEY (id),
    CONSTRAINT ukstw573p7lmwup5wjsvff7vs6i UNIQUE (cnpj_cpf)
    );

CREATE TABLE IF NOT EXISTS public.comanda
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ativa boolean NOT NULL,
    data_hora_abertura timestamp(6) without time zone NOT NULL,
    data_hora_fechamento timestamp(6) without time zone,
    nome_consumidor character varying(255) COLLATE pg_catalog."default",
    numero_mesa integer NOT NULL,
    observacao character varying(255) COLLATE pg_catalog."default",
    status character varying(255) COLLATE pg_catalog."default",
    taxa_servico double precision NOT NULL,
    total double precision NOT NULL,
    mesa_id bigint NOT NULL,
    CONSTRAINT comanda_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.comanda_itens
(
    comanda_id bigint NOT NULL,
    itens_id bigint NOT NULL,
    CONSTRAINT ukley3ye35j5nq8iqqaqo7ufplj UNIQUE (itens_id)
    );

CREATE TABLE IF NOT EXISTS public.funcionario
(
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default" NOT NULL,
    id bigint NOT NULL,
    restaurante_id bigint NOT NULL,
    CONSTRAINT funcionario_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.item
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    categoria character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descricao character varying(255) COLLATE pg_catalog."default",
    disponibilidade boolean NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    preco double precision NOT NULL,
    CONSTRAINT item_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.mesa
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    disponibilidade boolean NOT NULL,
    numero_mesa integer NOT NULL,
    garcom_id bigint NOT NULL,
    restaurante_id bigint NOT NULL,
    CONSTRAINT mesa_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.restaurante
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cnpj character varying(255) COLLATE pg_catalog."default" NOT NULL,
    bairro character varying(255) COLLATE pg_catalog."default",
    cep character varying(255) COLLATE pg_catalog."default",
    cidade character varying(255) COLLATE pg_catalog."default",
    complemento character varying(255) COLLATE pg_catalog."default",
    estado character varying(255) COLLATE pg_catalog."default",
    logradouro character varying(255) COLLATE pg_catalog."default",
    numero character varying(255) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    telefone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    proprietario_id bigint NOT NULL,
    CONSTRAINT restaurante_pkey PRIMARY KEY (id),
    CONSTRAINT uk6541lrwirgrv2uykx87fc4saa UNIQUE (cnpj)
    );

CREATE TABLE IF NOT EXISTS public.role
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT role_pkey PRIMARY KEY (id),
    CONSTRAINT ukpsbnsrja0jvuncak7b0sqo2fi UNIQUE (nome)
    );

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    senha character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id),
    CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email)
    );

CREATE TABLE IF NOT EXISTS public.usuario_role
(
    usuario_id bigint NOT NULL,
    role_id bigint NOT NULL
);

ALTER TABLE IF EXISTS public.cardapio
    ADD CONSTRAINT fkg9apwip11cu5x8g26l64nvhre FOREIGN KEY (restaurante_id)
    REFERENCES public.restaurante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cardapio_itens
    ADD CONSTRAINT fkh6gwdbfwnmyj1qotu36l41fdq FOREIGN KEY (cardapio_id)
    REFERENCES public.cardapio (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cardapio_itens
    ADD CONSTRAINT fkqgm93nvsc23ducr85v6qgt8di FOREIGN KEY (itens_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uktl48nqlfe96ekyota417v0wy3
    ON public.cardapio_itens(itens_id);


ALTER TABLE IF EXISTS public.cliente
    ADD CONSTRAINT fksitxst8o302fspskxfjatuyrl FOREIGN KEY (id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS cliente_pkey
    ON public.cliente(id);


ALTER TABLE IF EXISTS public.comanda
    ADD CONSTRAINT fkrjvp490ta9glh273c7pop1r61 FOREIGN KEY (mesa_id)
    REFERENCES public.mesa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comanda_itens
    ADD CONSTRAINT fk621xwq1aggyjgfw83dfupbt69 FOREIGN KEY (itens_id)
    REFERENCES public.item (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukley3ye35j5nq8iqqaqo7ufplj
    ON public.comanda_itens(itens_id);


ALTER TABLE IF EXISTS public.comanda_itens
    ADD CONSTRAINT fkewb9qarbaqmf16lsqdlec2lbg FOREIGN KEY (comanda_id)
    REFERENCES public.comanda (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.funcionario
    ADD CONSTRAINT fkgq1srs9sf3lvyea6qcflllu5l FOREIGN KEY (restaurante_id)
    REFERENCES public.restaurante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.funcionario
    ADD CONSTRAINT fkjsvlnmymcpdtn32hfainpxb7f FOREIGN KEY (id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS funcionario_pkey
    ON public.funcionario(id);


ALTER TABLE IF EXISTS public.mesa
    ADD CONSTRAINT fkpebnxug9x5va47ryok0buyesb FOREIGN KEY (restaurante_id)
    REFERENCES public.restaurante (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.mesa
    ADD CONSTRAINT fkt88aatg6m40gm0wi1uym6t8dd FOREIGN KEY (garcom_id)
    REFERENCES public.funcionario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.restaurante
    ADD CONSTRAINT fkhqf2qgf9rfad46w56aqv3cmkm FOREIGN KEY (proprietario_id)
    REFERENCES public.cliente (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario_role
    ADD CONSTRAINT fke7gfguqsiox6p89xggm8g2twf FOREIGN KEY (role_id)
    REFERENCES public.role (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.usuario_role
    ADD CONSTRAINT fkpc2qjts6sqq4hja9f6i3hf0ep FOREIGN KEY (usuario_id)
    REFERENCES public.usuario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;